### ISSUE TITLE
Suggestion: Interactive REPL plots

### ISSUE THREAD

**Issue by Symbolics** [komi1230/kai#13]
Not sure how this could be done or I'd take a stab at it. Interactive plots, being able to manipulate the data and add labels, change scales, etc from the REPL would be an awesome feature for Kai. Perhaps by opening up a websocket and connecting to the browser that way?

**Comment by Symbolics** [comment]
Whilst researching a current project I found [huchensockets](https://github.com/easye/hunchensocket), an implementation of websockets. Thought it might be useful if anyone pursues the idea of interactive plots.

**Comment by Symbolics** [comment]
[Slime-proxy](https://github.com/3b/slime-proxy) might also be helpful. It's a proxy between a slime REPL and a browser and uses websockets. It's designed to be used with Parenscript. Speaking of [Parenscript](https://common-lisp.net/project/parenscript/), seems that would be a useful tool for Kai to help with the JavaScript generation.

**Comment by komi1230** [comment]
Your PR is welcome.

**Comment by Symbolics** [comment]
Way beyond my abilities.

Just using the issue to record projects that might be relevant. If the links aren't helpful, happy to close the issue.

**Comment by komi1230** [comment]
To be honest, this feature is not included in my use cases, and I'm not interested in this.

So, I'm not motivated to implement this.

If you don't commit this project with your code, this issue is over.

Can I close this issue?

**Comment by Symbolics** [comment]
Yes please close.

    On Sunday, August 9, 2020, 10:53:24 AM GMT+8, komi <notifications@github.com> wrote:  
 
 


To be honest, this feature is not included in my use cases, and I'm not interested in this.

So, I'm not motivated to implement this.

If you don't commit this project with your code, this issue is over.

Can I close this issue?
