### ISSUE TITLE
Inserting plot size into plot via JavaScript

### ISSUE THREAD

**Issue by Symbolics** [komi1230/kai#20]
Is there a way to insert the plot size into the generated JavaScript? Trying to open a browser with a specified size is fraught with difficulties and, even when it can be done, the user has to guess at what a good initial size might be. The methods to do this from a command line also vary across browsers.

It seems that the 'correct' way to do this is via JavaScript in the generated web page. Perhaps a reasonable initial default could be provided, e.g. `*kai-default-plot-size*` and then the user or plotly/GR could update this value if they needed something bigger.

**Comment by komi1230** [comment]
Hello,

It is a pity to say that this repository is not actively maintained, and this will be archived.
If you want more features, fork this and maintain by yourself.

Thanks
