### ISSUE TITLE
Can't open a browser on Windows 10

### ISSUE THREAD

**Issue by poco919** [komi1230/kai#9]
Plot files (kai.html and others) are perfectly created but a browser cannot be opened from CLI.
Instead of opening a browser, a file explorer is opened. 

I think the problem is on a trivial-open-browser used package in kai.
I tried to open kai.html using a function of a trivial-open-browser and found the same bug.
trivial-open-browser uses a command of explorer for opening a file (or URL) using a UIOP.

I couldn't figure out though, a command of " explorer 'sample.html' " doesn't work on my enviroment. (a command of  "explorer 'URL' " successfully works.)

So, it might be suggested to use a different package instead of a trivial-open-browser.

-Environment-
Windows 10
Run Rosewell on PowerShell

**Comment by komi1230** [comment]
Hello poco.
Thank you for contributing to this project and making issue.
It seems this issue of yours is the first OSS contribution.
Welcome to geeks world !

OK, let's get started to discuss this issue.

Now I've checked if `explorer` command works fine in my environment (PowerShell in Windows10), and I've found this is OK.
I've done this command:

```bash
$ echo "hello" > sample.html
$ explorer sample.html
```

If `explorer` command doesn't work in your environment, it seems there is some trouble.
Can you re-check why `explorer` command doesn't work in your environment ?

**Comment by poco919** [comment]
Thank you for the welcome!

I've checked the command above, and it works properly.
So, I could run the command below too
`$ explorer C:\Users\Username\.cache\kai\plotly\kai.html`
(When I use UIOP package, it doesn't work, So I figured this is an issue of the library.)

I rechecked the error message.
It shows 
> Subprocess with command "explorer \"C:/Users/Username/.cache/kai/plotly/kai.html\""
> exited with error code 1

It seems due to the path.
Sorry for my carelessness and thank you for the quick reply.

**Comment by komi1230** [comment]
I've actually got some reports just like that: Path is not proper in Windows.

I'll fix it sooner or later.
But it may take time because my main laptop is Macbook and I'm not familiar with Windows.
Your PR is also welcome :)

**Comment by komi1230** [comment]
fixed.
see [this commit](https://github.com/komi1230/kai/commit/3e0c5cefa19fd21e1ca509f1981cb17e2070b68b)

**Comment by poco919** [comment]
Kai properly works on my environment too.
Thank you for the quick fix!
